version: '3'
services:
  api:
    image: ghcr.io/mharikmert/education-portal/api:latest
    container_name: portal-api-container
    build:
      context: ./backend/spring
    ports:
      - 8080:8080
    # env_file:  -> specify your environment variables here
    #   - some.env

  client:
    image: ghcr.io/mharikmert/education-portal/client:latest
    container_name: portal-client-container
    build:
      context: ./frontend/angular
    ports:
      - 80:80
      - 443:443
