version: '3'
services:
  nginx:
    image: ghcr.io/mharikmert/education-portal/nginx:latest
    container_name: portal-nginx-container
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  api:
    image: ghcr.io/mharikmert/education-portal/api:latest
    container_name: portal-api-container
    build:
      context: ./backend/spring

  client:
    image: ghcr.io/mharikmert/education-portal/client:latest
    container_name: portal-client-container
    build:
      context: ./frontend/angular
